Name: opengate
Build: local
Controller: 
  Port: 8080
  GinModeDebug: false
  Ping:
    DB: true
  Config:
    DB: true
Repository:
  Name: MONGO
  Mongo: 
    Host: localhost:27017
    Database: opengate
    UserName: bappa
    Password: bappa
Cache:
  Name: Redis
  Redis:
    Addr: localhost:6379
    Password:
    DB: 0
  